// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PodFilesystemSyncListerExpansion allows custom methods to be added to
// PodFilesystemSyncLister.
type PodFilesystemSyncListerExpansion interface{}

// PodFilesystemSyncNamespaceListerExpansion allows custom methods to be added to
// PodFilesystemSyncNamespaceLister.
type PodFilesystemSyncNamespaceListerExpansion interface{}
