// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	riotkitorgv1alpha1 "github.com/riotkit-org/volume-syncing-operator/pkg/apis/riotkit.org/v1alpha1"
	versioned "github.com/riotkit-org/volume-syncing-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/riotkit-org/volume-syncing-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/riotkit-org/volume-syncing-operator/pkg/client/listers/riotkit.org/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodFilesystemSyncInformer provides access to a shared informer and lister for
// PodFilesystemSyncs.
type PodFilesystemSyncInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PodFilesystemSyncLister
}

type podFilesystemSyncInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodFilesystemSyncInformer constructs a new informer for PodFilesystemSync type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodFilesystemSyncInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodFilesystemSyncInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodFilesystemSyncInformer constructs a new informer for PodFilesystemSync type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodFilesystemSyncInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RiotkitV1alpha1().PodFilesystemSyncs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RiotkitV1alpha1().PodFilesystemSyncs(namespace).Watch(context.TODO(), options)
			},
		},
		&riotkitorgv1alpha1.PodFilesystemSync{},
		resyncPeriod,
		indexers,
	)
}

func (f *podFilesystemSyncInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodFilesystemSyncInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podFilesystemSyncInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&riotkitorgv1alpha1.PodFilesystemSync{}, f.defaultInformer)
}

func (f *podFilesystemSyncInformer) Lister() v1alpha1.PodFilesystemSyncLister {
	return v1alpha1.NewPodFilesystemSyncLister(f.Informer().GetIndexer())
}
