/*
Copyright Riotkit.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/riotkit-org/volume-syncing-controller/pkg/apis/riotkit.org/v1alpha1"
	scheme "github.com/riotkit-org/volume-syncing-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PodFilesystemSyncsGetter has a method to return a PodFilesystemSyncInterface.
// A group's client should implement this interface.
type PodFilesystemSyncsGetter interface {
	PodFilesystemSyncs(namespace string) PodFilesystemSyncInterface
}

// PodFilesystemSyncInterface has methods to work with PodFilesystemSync resources.
type PodFilesystemSyncInterface interface {
	Create(ctx context.Context, podFilesystemSync *v1alpha1.PodFilesystemSync, opts v1.CreateOptions) (*v1alpha1.PodFilesystemSync, error)
	Update(ctx context.Context, podFilesystemSync *v1alpha1.PodFilesystemSync, opts v1.UpdateOptions) (*v1alpha1.PodFilesystemSync, error)
	UpdateStatus(ctx context.Context, podFilesystemSync *v1alpha1.PodFilesystemSync, opts v1.UpdateOptions) (*v1alpha1.PodFilesystemSync, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PodFilesystemSync, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PodFilesystemSyncList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PodFilesystemSync, err error)
	PodFilesystemSyncExpansion
}

// podFilesystemSyncs implements PodFilesystemSyncInterface
type podFilesystemSyncs struct {
	client rest.Interface
	ns     string
}

// newPodFilesystemSyncs returns a PodFilesystemSyncs
func newPodFilesystemSyncs(c *RiotkitV1alpha1Client, namespace string) *podFilesystemSyncs {
	return &podFilesystemSyncs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the podFilesystemSync, and returns the corresponding podFilesystemSync object, and an error if there is any.
func (c *podFilesystemSyncs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PodFilesystemSync, err error) {
	result = &v1alpha1.PodFilesystemSync{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podfilesystemsyncs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PodFilesystemSyncs that match those selectors.
func (c *podFilesystemSyncs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PodFilesystemSyncList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PodFilesystemSyncList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podfilesystemsyncs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested podFilesystemSyncs.
func (c *podFilesystemSyncs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("podfilesystemsyncs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a podFilesystemSync and creates it.  Returns the server's representation of the podFilesystemSync, and an error, if there is any.
func (c *podFilesystemSyncs) Create(ctx context.Context, podFilesystemSync *v1alpha1.PodFilesystemSync, opts v1.CreateOptions) (result *v1alpha1.PodFilesystemSync, err error) {
	result = &v1alpha1.PodFilesystemSync{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("podfilesystemsyncs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(podFilesystemSync).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a podFilesystemSync and updates it. Returns the server's representation of the podFilesystemSync, and an error, if there is any.
func (c *podFilesystemSyncs) Update(ctx context.Context, podFilesystemSync *v1alpha1.PodFilesystemSync, opts v1.UpdateOptions) (result *v1alpha1.PodFilesystemSync, err error) {
	result = &v1alpha1.PodFilesystemSync{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podfilesystemsyncs").
		Name(podFilesystemSync.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(podFilesystemSync).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *podFilesystemSyncs) UpdateStatus(ctx context.Context, podFilesystemSync *v1alpha1.PodFilesystemSync, opts v1.UpdateOptions) (result *v1alpha1.PodFilesystemSync, err error) {
	result = &v1alpha1.PodFilesystemSync{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podfilesystemsyncs").
		Name(podFilesystemSync.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(podFilesystemSync).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the podFilesystemSync and deletes it. Returns an error if one occurs.
func (c *podFilesystemSyncs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podfilesystemsyncs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *podFilesystemSyncs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podfilesystemsyncs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched podFilesystemSync.
func (c *podFilesystemSyncs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PodFilesystemSync, err error) {
	result = &v1alpha1.PodFilesystemSync{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("podfilesystemsyncs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
